# note this must be created on DUC server and values copied in; should be ignored by git
API_TOKEN: "G3UrfZGRiWGDd4xHt7ZLdJNkEYSt2EKYjSrDxW0XGjy5OFFTdBAM6xYjpFpV2FNaxTPpmoIBdNMxJMXWnReDOg"
SHARED_SECRET: "83F_H1XcW6nIW-UDvEbaTUPWp5q42IazNHpKZ67exoA"
DOMAIN_NAME: "example_domain"